language: python
python: 3.6
env:
- TOXENV=py27,py35
install: pip install tox-travis
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: magizbox
  password:
    secure: "mUCZOoHJbAHXxZdJ87oRLW/2IaBuMM5cXiipW8OZGOTVDp0qPPXeuRuvTvWOlBJiELrek8R0ynQoFaJsmE3Zx0TQluyg+xvHNx1UGCnLvjrGOztLFRc6YPyp7PaOfOqqJpDPPqmkw4L+c+ZxPjlc6aCrrBspuK1qOJh5Q+o+ledlfGkW7jEWVJdR0JfFfRUvBx093EozQBD+jdDGDwAN2fwXP1QyBPvuKITmiYQzKmEbu3EtrLlOyVqTGWRXdjtRFQjWgvTvq0/pQv7q/n1kNkM9UFfbXNnF3ORtFHk+NlVKXBN94Duoj6j8xneZw60iLXaU9DUs0ITFaE3LFvrzHUUG1NvO6/Yi9kp5wiysbpHNVZSXj+Dz307r5K5yZqTnMtjk+V1uUIi8E9zctlf704Ma+EYgJqRvMLmTJ4wiiEgGMJtYNjqxP+5SOahZe4JQ20uxuDKc6SfjCq46F4anRbJzzYUec8HakWJN9z955Mq4fVJ3u/BvKA9o2NntSEJ0PVhULO+AKoEK52M6yc70YkVxZYGQMf/9hlDO0jQ0Mgx+Eo5+MpQRivOYskHi1Qxc4j5q26phNFscuUlN5SNTjQvhDFAiYm/DiDfgQNBqRT325NS7iy8yLa0oV9/3zVKlD/inqH4puDAm5sWka3X4ZT6ORY3S08sJUBhuNDGp9nk="
